--Ver la descripción entera de un producto en una línea
SELECT
F_NAN_KEY               "NANKEY"
,AC_NANDESCRSHORT       "DESCRIPTION"
,NC_PERACTIVEFROM       "ACTIVE FROM"
,NC_PERACTIVETO         "ACTIVE TO"
,DT_CREATED_DATE        "CREATED DATE"
,DT_LAST_CHANGED_DATE   "LAST CHANGED DATE"
FROM VLDIMDB_ES.NANS        
WHERE F_NAN_KEY IN ('57292310');