--(1)CARACTERÍSTICAS LOCALES Y CAMBIOS 2020 EN OGRDS
SELECT DISTINCT
--A.NC_CHARID,
B.F_NCV_NAN_KEY              AS  NANKEY
,C.AC_CHARDESCRIPTION        AS  CHARS
,A.AC_CHARVALUETAG           AS  CHAR_VALUE
,B.F_NCV_LAST_CHANGED_DATE   AS  LAST_CHANGED

FROM  
VLDIMDB_ES.CHARVALS         A
,VLDIMDB_ES.NANCHARVALS     B
,VLDIMDB_ES.CHARS           C
,VLDRAWDATA_ES.RAWDATA      D

WHERE  
B.F_NCV_NAN_KEY     IN     (62698951)
AND     A.NC_CHARID         =       B.NC_CHARID
AND     A.NC_CHARVALUEID    =       B.NC_CHARVALUEID
AND     A.NC_CHARID         =       C.NC_CHARID
AND     B.F_NCV_NAN_KEY     =       D.F_NAN_KEY

--AND     B.F_NCV_LAST_CHANGED_DATE   >      '01/02/20'
--AND    C.AC_CHARDESCRIPTION         LIKE   '#ES%'
--AND A.AC_CHARVALUETAG LIKE '%LIMASOL%'

ORDER BY B.F_NCV_NAN_KEY, C.AC_CHARDESCRIPTION ASC;